In [10]:
people = {'hugh':49,'kate':35,'lucy':24,'bob':36}

In [11]:
total = 0
for key in people:
     total += key

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [15]:
peoplelist = [{'name':'bob','age':28},{'name':'dylan','age':43},{'name':'cat','age':17}]
for item in peoplelist:
      if item['age']>30:
       print(item['name'])

dylan


In [18]:
def mystery(x):
      if x > 0:
          return -x
      else:
          return x

In [22]:

mystery(-5)

-5

In [24]:
import numpy as np
c = np.array([[2,4,6,8],[12,14,16,18],[22,24,26,28]])


In [26]:
print(c)


[[ 2  4  6  8]
 [12 14 16 18]
 [22 24 26 28]]


In [27]:
c.shape

(3, 4)

In [28]:
#Indexing the second row
c[1,:]

array([12, 14, 16, 18])

In [29]:
d = np.array([6,16,26])

In [30]:
#Apply a boolean mask so that all numbers greater than 10 are zero
d[d>10]=0
d

array([6, 0, 0])

In [32]:
word_freq = {'the':58, 'people':6, 'beautiful':8, 'cats':13, 'finally':9, 'this': 19, 'class': 21, 'is': 101, 'almost': 1, 'over':4}

In [34]:
def eval_freq(i_dict,t):
    above_threshold = {}
    for key, value in i_dict.items():
        if value > t:
            above_threshold[key] = value
    
    return above_threshold
    

In [35]:
eval_freq(word_freq, 10)

{'the': 58, 'cats': 13, 'this': 19, 'class': 21, 'is': 101}

In [71]:
import pandas as pd
#Read in the data
df = pd.read_csv('eur.pop.rev.csv', delimiter=',', header = 0)
# Rename the screwy column names
df = df.rename(columns={'European Population (1989-1995)':'Country', 'Unnamed: 1':'1989', 'Unnamed: 2':'1990', 'Unnamed: 3':'1991', 'Unnamed: 4':'1992',
                        'Unnamed: 5':'1993', 'Unnamed: 6':'1994', 'Unnamed: 7':'1995'})
# Drop the whitespace
df = df.drop([0, 1])
# Replace NA data with 0
df = df.fillna(0)
# Change columns to numeric
df['1989'] = pd.to_numeric(df['1989'])
df['1990'] = pd.to_numeric(df['1990'])
df['1991'] = pd.to_numeric(df['1991'])
df['1992'] = pd.to_numeric(df['1992'])
df['1993'] = pd.to_numeric(df['1993'])
df['1994'] = pd.to_numeric(df['1994'])
df['1995'] = pd.to_numeric(df['1995'])

print('Countries over a million avg population, 1995')
print('')
for index, row in df.iterrows():
    if row['1995'] > 1000000:
        print(f"Country: {row['Country']}, Population '95: {row['1995']}")


Countries over a million avg population, 1995

Country: Austria, Population '95: 8054800
Country: Belgium, Population '95: 10143047
Country: Denmark, Population '95: 5251027
Country: Finland, Population '95: 5116800
Country: France, Population '95: 58265400
Country: Germany, Population '95: 81845000
Country: Ireland, Population '95: 3591200
Country: Italy, Population '95: 57268578
Country: Netherland, Population '95: 15492800
Country: Norway, Population '95: 4370000
Country: Portugal, Population '95: 9920800
Country: Spain, Population '95: 39241900
Country: Sweden, Population '95: 8837000
Country: Switzerland, Population '95: 7060400
Country: United Kingdom, Population '95: 58684000
Country: Total Europe, Population '95: 372599752


In [67]:
my_df= df.set_index('Country')
print('Population of UK in 1989-95')
my_df.loc['United Kingdom']

Population of UK in 1989-95


1989    57236200
1990    57410600
1991    57649200
1992    58888800
1993    58191230
1994    58380000
1995    58684000
Name: United Kingdom, dtype: int64

In [59]:
print(df.index.tolist())

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
