In [1]:
import numpy as np

In [2]:
myarray = np.arange(1, 21).reshape(4, 5)

In [3]:
print(myarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
##I don't think this is what they want
myarray[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [9]:
myrows = myarray[2:4,:]
mycolumns = myarray[:,2:4]

print(myrows)
print(mycolumns)

[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


In [11]:
column_sums = np.sum(myarray, axis=0)
print(column_sums)

[34 38 42 46 50]
